services:
    db:
        container_name: filharmonia-db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USERNAME:-admin}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
            POSTGRES_DB: ${DB_NAME:-filharmonia}
        ports:
            - "6543:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
        driver: local
